### ISSUE TITLE
训练损失函数哪里的问题

### ISSUE THREAD

**Issue by CyberFox-lab** [chengstone/movie_recommender#2]
#简单的将用户特征和电影特征做矩阵乘法得到一个预测评分
      inference = tf.matmul(user_combine_layer_flat, tf.transpose(movie_combine_layer_flat))

这里得到的是个矩阵，不能直接和Y计算吧

   这里应该用点乘吧。
   inference = user_combine_layer_flat*movie_combine_layer_flat

**Comment by chengstone** [comment]
是的 您说的对 这里应该用点乘求和，代码已经修改
