### ISSUE TITLE
你好，关于movieID的个数问题

### ISSUE THREAD

**Issue by ZuoxiYang** [chengstone/movie_recommender#4]
movieID值中间是有空缺的，这个的代码注释写着是求movieID的个数，但是实际上是求movieID的最大值，然后在后面的#电影名单词个数movie_title_max = len(title_set) # 5216，这里又是求电影名的个数，被搞蒙了。所以这里到底是求movieID的个数还是最大值呢？为什么两者都能成立呢？后面的movie_id_embed_matrix = tf.Variable(tf.random_uniform([movie_id_max, embed_dim], -1, 1), name = "movie_id_embed_matrix")，这里会用到这个数值做Embedding啊，希望能解答一下，谢谢。

**Comment by chengstone** [comment]
你好 很抱歉过了这么久才回复你 不知道你是否已经想明白了这个问题 这里简单解释一下
感觉你好像没有弄清楚movie_id_max和movie_title_max的意图，movieID中间是有空缺的，所以可以忽略空缺，只取最大值就行了，比如movieID一共有5个，分别是1、2、5、8、9，那么取得的movie_id_max就是9，虽然只有5个，但是我得给那些空缺的ID在嵌入矩阵中预留位置。
另外movie_title_max说的很明白啊，是电影名的个数，这跟movie_id_embed_matrix没关系啊。
你再想想。
